name: 'Install Using PyPI'
description: 'Setup environment and install using the PyPI-based toolchain'
inputs:
  need-extras:
    description: 'Whether to install the extras'
    required: false
    default: 'false'
  type:
    description: 'Whether test or doc build'
    required: true
  version-file:
    description: 'Name of the version file to use for installation'
    required: false
    default: 'requirements.txt'
  python-version:
    description: 'What version of Python to use'
    required: true
  old-build:
    description: 'Whether to enable old builds for shapely and cartopy'
    required: false
    default: 'false'
  need-cartopy:
    description: 'Whether Cartopy support is needed'
    required: false
    default: 'false'
  install-target:
    description: ''
    required: false
    default: '.'
  install-flags:
    description: ''
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python-version }}
        cache-dependency-path: |
          ci-dev/${{ inputs.type }}_requirements.txt
          ci/${{ inputs.version-file }}
          ci/extra_requirements.txt

    - uses: astral-sh/setup-uv@v7

    - name: Set dependency groups for install
      shell: bash
      run: |
        if [[ ${{ inputs.need-extras }} == 'true' ]]
        then
          echo "DEP_GROUPS=${{ inputs.type }},extras" >> $GITHUB_ENV
        else
          echo "DEP_GROUPS=${{ inputs.type }}" >> $GITHUB_ENV
        fi

    - name: Set install flags
      shell: bash
      run: echo "INSTALL_FLAGS=${{ env.INSTALL_FLAGS }}" >> $GITHUB_ENV

    - name: Massage for backwards compatibility
      if: ${{ inputs.version-file && (inputs.install-flags == '') }}
      shell: bash
      run: echo "INSTALL_FLAGS=-c ci/${{ inputs.version-file }} -c ci-dev/${{ inputs.type }}_requirements.txt -c ci/extra_requirements.txt" >> $GITHUB_ENV

    - name: Install
      shell: bash
      run: >
        uv pip install --system ${{ env.INSTALL_FLAGS }} ${{ inputs.install-target }}[${{ env.DEP_GROUPS }}]

    - name: Install additional test tools
      if: ${{ inputs.type == 'test' }}
      shell: bash
      run: >
        uv pip install --system $${{ env.INSTALL_FLAGS }} coverage

    - name: Download Cartopy Maps
      if: ${{ inputs.need-cartopy == 'true' }}
      shell: bash
      run: ci/download_cartopy_maps.py

